### ISSUE TITLE
communication

### ISSUE THREAD

**Issue by So871** [little-chef/intergas-xtreme-monitor#1]
Hey kerel, 
ik probeer jouw code met esphome en een 8266, echter krijg ik er geen data uit.
heb een hre , en gebruik de rx en tx pinnen,

hardware werkt wel met de code van meewis met mqtt en node red,.
![image](https://user-images.githubusercontent.com/45521085/209431000-1b01281a-9d13-413f-a1ad-495853619848.png)

**Comment by little-chef** [comment]
Hoi,
Deze code is gemaakt voor de Xtreme serie en niet de HRE. Het protocol met de ketel is anders, de Xtreme heeft allerlei CRC checks die de HRE niet heeft en de data zit op andere plaatsen in de berichten. Ik verwacht dat dit alleen verkeerde resultaten geeft, maar wel degelijk iets van data.

Bij de 8266 worden in dit project de pinnen van UART0 geremapped naar andere pinnen om te voorkomen dat de bootlogging van esphome naar de ketel gestuurd wordt die mogelijk enkele random instellingen van de ketel zou kunnen overschrijven.
Waarschijnlijk gebruik je de verkeerde pinnen voor rx en tx. In de documentatie bij de code staat precies hoe je het aan moet sluiten.

Daarbij gebruik ik de 8266 niet meer omdat deze tegen memory fragmentatie issues aanloopt waardoor wifi traag en instabiel wordt zodat over-the-air updates niet meer werken. Alleen de esp32 is nog ondersteunt.
![image](https://user-images.githubusercontent.com/110604884/209546676-5e20db06-55e1-4124-b670-33dc0f1956bb.png)

**Comment by So871** [comment]
Dank voor de reactie , 

Ik heb hier zelf helaas niet genoeg kaas van gegeten om de code aan te passen. 

Ik gebruik gpio 1 en 3 , een vriend van mij heeft het schema van keesma vertaald naar een custom pcb.

Als ik de data onderschep met een ttl stick met jou code zie ik wel degelijk S?/r binnenkomen , dus verzenden gaat goed.
Nu nog zien uit te vogelen waarom de ketel geen antwoord geeft.

**Comment by little-chef** [comment]
De mainline code is alléén voor de ESP32. Werkt niet met de ESP8266. Ook is de code voor de Xtreme, en niet de HRE.
In de historie zie je een commit die de support voor ESP8266 verwijderd, de laatste commit daar voor zou moeten werken mits je GPIO13 en GPIO15 gebruikt, en als het werkt is wifi niet stabiel. Als je GPIO 1 en 3 wilt gebruiken moet je die code aanpassen, en wordt het nog leuk als je zo af en toe spontaan wat instellingen ziet veranderen in de ketel. 
Het schema van keesma komt niet overeen met het schema wat in dit project staat, de code is alleen geschreven voor en getest met het schema in dit project. In dat schema van keesma zit ook een fout:
![image](https://user-images.githubusercontent.com/110604884/209850979-2c68fd1d-cae3-4dde-8afb-d806ca8e69cc.png)
De ketel levert 5 volt op de pin (in ieder geval bij de Xtreme) , niet 3V3, en de Tx/Rx lijnen zijn niet 5V compatible. De signalen leveren dus te hoge spanningen terug naar de ketel. Dit kan die poort beschadigen.

**Comment by So871** [comment]
Duidelijk, 

Correctie : niet het schema van Keesma maar van Meewis gebruikt.
Maar ook die is 3.3V
![Screenshot_2022-12-29-09-22-15-33_320a9a695de7cdce83ed5281148d6f19.jpg](https://user-images.githubusercontent.com/45521085/209924510-cb85c1cf-c26c-46ee-9a3b-fa4630fa89dd.jpg)

Ik ga jouw schema nabouwen en kijken of ik er dan leven uit krijg.
Met jouw code als basis moet ik toch een heel eind in de buurt zitten.

**Comment by So871** [comment]
hey kerel, 
ik heb met de esp32 weinig succes met de hre, ik zie een response maar dat is een bijzonder vreemd response
met in laatste commit naar esp8266 en de aangepaste punten krijg ik er netjes antwoord van.
weliswaar met de OTA problemen waar je voor waarschuwde.
maar ben zelf geen ster in c++ dus het is mij een raadsel waarom ik nu geen normaal response krijg,
 jij misschien een idee?

![image](https://user-images.githubusercontent.com/45521085/211149922-bec1c1a2-f630-4165-8538-d91cf0f7808a.png)

**Comment by little-chef** [comment]
In een goede situatie krijg je precies 32/33 bytes binnen, dit lijkt random data, lijkt alsof de verkeerde pin gebruikt worden voor de rx lijn.

**Comment by tim427** [comment]
> hey kerel, ik heb met de esp32 weinig succes met de hre, ik zie een response maar dat is een bijzonder vreemd response met in laatste commit naar esp8266 en de aangepaste punten krijg ik er netjes antwoord van. weliswaar met de OTA problemen waar je voor waarschuwde. maar ben zelf geen ster in c++ dus het is mij een raadsel waarom ik nu geen normaal response krijg, jij misschien een idee?
> 
> ![image](https://user-images.githubusercontent.com/45521085/211149922-bec1c1a2-f630-4165-8538-d91cf0f7808a.png)

@So871 heb je de aangepaste versie ergens online staan? En https://github.com/little-chef/intergas-xtreme-monitor/issues/4#issuecomment-1839169443 heb je het over jouw versie van PCB ergens gedeeld te hebben; ik ben zeer geïnteresseerd ;)
