### ISSUE TITLE
going offline in the morning

### ISSUE THREAD

**Issue by So871** [little-chef/intergas-xtreme-monitor#2]
hello,  ( goede morgen)

i'm having some issues with my setup on a HRE, i adopted your code and edited the datapoints, so far so good,
but for some reason the node keeps going offline, especially in the morning ( 06:00-07:00) when i try to log it serially , at the moment is goes offline the output starts giving gibberish ,

is there anything in the code that can explain a timed issue ?

**Comment by little-chef** [comment]
Hi,
In my case the instance is now running for 280 hours 53 minutes and 35 seconds, that is is since the last update op ESPHome I did. in my case the only reason to reboot the device is because of updates, apart from that it is rock solid. So, no: I cannot explain it from code perspective. 
If hangup is time specific during the night you need to wonder if the wifi access point is not rebooting at that time, and the wifi connection just gets recovered poorly.

**Comment by renini** [comment]
First of all, very cool project, thanks for all the hard work. I have something similar, with an Xtreme 36. Although i haven't pinpointed it to the morning yet, (only have it connected for 3 days), but had to power cycle 3 times also. Will do some more digging and see if I can get console output. Wifi signal shouldn't be the issue in my case at least, feels more like a memory leak thing as it seems to take some time before being "unavailable".

**Comment by little-chef** [comment]
If it would be memory leaks, it would not explain why it runs for many weeks in my case, and 3 days somewhere else. I do have a bunch of onewire sensors connected to it. If there are no one-wire sensors then perhaps it is better to disable it altogether in the yaml file.

**Comment by renini** [comment]
I agree, i had disabled the onewire code, as i suspected this might be causing it too, but it still happened. For example last night, with a ping/icmp monitor i noticed that the esp32 missed 3 pings around 03:34 last night; at 04:44 it was up again, only to go down again at 05:25, which it currently still is (unfortunately i have no logging), I will investigate some more to see if i can correlate more information and get logging. 

What model Xtreme are you having yourself?
