### ISSUE TITLE
PCB Design

### ISSUE THREAD

**Issue by thoutenbos** [little-chef/intergas-xtreme-monitor#4]
Love this project! Cannot wait to hook it up to my new Xtreme 30

Do you happen to have a PCB design already?

**Comment by little-chef** [comment]
Hi,
No, not yet something shareable. 
It is a pretty simple schematic, so an experimental PCB should work too.

**Comment by renini** [comment]
@So871 might be able to share his pcb design in gerber files?
I have v3 of his pcb design, but this seems to have an issue where the 5v input line interference might be causing the esp32 to hang over time.

![image](https://github.com/little-chef/intergas-xtreme-monitor/assets/1587083/41c44597-5d5c-47b9-a388-ba913702e480)

See: https://www.circuitsonline.net/forum/view/80667/last

**Comment by So871** [comment]
> @So871 might be able to share his pcb design in gerber files? I have v3 of his pcb design, but this seems to have an issue where the 5v input line interference might be causing the esp32 to hang over time.
> 
> ![image](https://private-user-images.githubusercontent.com/1587083/287642479-41c44597-5d5c-47b9-a388-ba913702e480.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3MTI1NDksIm5iZiI6MTcwMTcxMjI0OSwicGF0aCI6Ii8xNTg3MDgzLzI4NzY0MjQ3OS00MWM0NDU5Ny01ZDVjLTQ3YjktYTM4OC1iYTkxMzcwMmU0ODAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDRUMTc1MDQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmZhN2I0NDA5YWYyODlmNWJjNjE0OTUyMzg5MDQyYWRmM2RjNzY5OGFlYmFlYzFlNWMyNTA1YzMzZDQ1YzI5ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4n8lZrFw0yWuWnwuFPrNqZjR2awfD9f2X3AZF2N5fpc)
> 
> See: https://www.circuitsonline.net/forum/view/80667/last

Hey sorry for the very long time off, some health issues and a mystic thing called time ..lol

I'll share the Gerber files and schematic for the PCB tomorrow
